# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Zs Speed Timer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Zs Speed Timer
  pod 'Alamofire', '~> 5.2'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod "GCDWebServer", "~> 3.0"
  pod "RealmSwift"

end
